/**
 * Image upload type definitions.
 *
 * Images are stored in S3; DynamoDB records store only the `image_asset_key` (S3 object key).
 * Upload uses a presigned S3 PUT URL generated by the backend.
 * Image field is optional for rewards, quest questions, and boss questions.
 *
 * URL import is intentionally deferred.
 * TODO later: support image import from URL by downloading server-side and storing in S3
 *
 * Delete behavior: pass `image_asset_key: null` in the entity update payload to detach the image.
 * TODO later: decide whether detached images should be deleted from S3 immediately
 *             or cleaned up by a background job.
 */

export type EntityType = "reward" | "quest-question" | "boss-question";

export type CreateImageUploadUrlRequest = {
    /** Teacher performing the upload. TODO: replace with JWT claim once auth is wired. */
    teacher_id: string;
    /** The entity type this image belongs to — determines the S3 folder. */
    entity_type: EntityType;
    /** MIME type of the image file. */
    content_type: "image/jpeg" | "image/png" | "image/gif" | "image/webp";
    /** Optional file size in bytes; validated server-side against the 5 MB limit. */
    file_size?: number;
};

export type CreateImageUploadUrlResponse = {
    /** Presigned S3 PUT URL — valid for 5 minutes. */
    uploadUrl: string;
    /** S3 object key to persist in DynamoDB as `image_asset_key`. */
    imageAssetKey: string;
};
